export {
  initializeDatabase,
  createNote,
  getAllNotes,
  getNoteById,
  updateNote,
  deleteNote,
  getDeletedNotes,
  permanentlyDeleteNote,
  restoreNote,
  setNoteFavorite,
  getFavoriteNotes,
  getDrawerStats,
  type NoteInput,
  type NoteRecord,
} from './database';
